docs/_navbar.md
docs/discord-verification-bot/index.md
docs/discord-verification-bot/privacy.md

feat: verification bot docs

---

docs/contributing.md
docs/index.html

Signed-off-by: takanome_dev <takanomedev221@gmail.com>
Add a link to the issue finder to help people find easily issues to work on.
Closes #10

docs: add issue finder link

---

docs/_navbar.md

chore: update avatar

---

docs/_navbar.md
docs/contributing.md
docs/labels.md

Adds a page which breaks down how we use labels in our projects.
Closes #14

feat: add label explanation

---

docs/_navbar.md
docs/ama-bot/index.md
docs/ama-bot/privacy.md
docs/ama-bot/usage.md

feat: ama bot documentation

---

docs/deepgram/self-hosting.md

feat: document option to run without ai, and bot permissions

---

docs/coc.md

feat: rewrite code of conduct

---

docs/_navbar.md
docs/coc.md
docs/index.html

feat: automatic nav bar expansion

---

docs/_navbar.md
docs/license.md

docs: add global license

---

docs/contributing.md
docs/license.md

docs: naomi's public license

---

docs/_navbar.md
docs/coc.md
docs/community/guide.md
docs/community/melody.md
docs/license.md
docs/staff/apply.md
docs/staff/start.md

feat: add community guidelines

---

docs/community/guide.md
docs/community/melody.md

feat: add information about plural systems

---

docs/contributing.md

feat: add note about holopin

---

docs/staff/start.md

feat: staff holopin badge

---

.github/workflows/md-lint.yml
package.json

chore: move to node 20

---

docs/staff/apply.md

chore: remove application links

---

docs/coc.md

feat: add clause about no ai

---

docs/community/melody.md

feat: update melody's documentation

---

docs/coc.md
docs/staff/moderator.md

docs: document the public modlog

---

docs/projects/deepgram/self-hosting.md
docs/projects/deepgram/usage.md

docs: update instructions for deepgram bot

---

docs/contributing.md

The package management section just seemed better gone, and the other changes were pretty easy. 
Closes #89

chore: remove extraneous npm mentions
